version: '3'

services:

  rabbitmq_app:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'  # The standard AMQP protocol port
      - '15673:15672'  # HTTP management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db_app:
    image: 'postgres:14'
    container_name: 'postgreSQL_db'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # сохраняем полученные данные здесь
      - ./rabbitmq/init.sql:/docker-entrypoint-initdb.d/init.sql  # специальная точка входа для инициализации БД
    ports:
      - '5433:5432'

  cron_docker:
    container_name: 'python_app'
    build:
      context: python_app
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq_app
      - db_app

